name: data_repository
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

