name: my_movie
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.0+4
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  cached_network_image: ^2.0.0
  video_player: ^0.10.8+1
  visibility_detector: ^0.1.5
  flick_video_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/videos/1.mp4
    - assets/icons/
  # example:
  fonts:
    - family: Vaud
      fonts:
        - asset: assets/fonts/Vaud-Bold.ttf
        - asset: assets/fonts/Vaud-Medium.otf
        - asset: assets/fonts/Vaud-SemiBold.otf
        - asset: assets/fonts/Vaud-Thin.otf
        - asset: assets/fonts/Vaud-Ultra.otf
        - asset: assets/fonts/Vaud-UltraLight.otf
        - asset: assets/fonts/Vaud.otf

