name: forsatbloc
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  data_repository:
    path: data_repository
  auth_repository:
    path: auth_repository

  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.2.0
  dio: ^3.0.9
  device_info: ^0.4.2+4
  shared_preferences: ^0.5.7+3
  loading_gifs: ^0.2.2
  flutter_spinkit: "^4.1.2"
  flutter_easyloading: ^1.1.4


  # UI
  settings_ui: ^0.3.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/en.json
    - assets/langs/km.json
    - assets/images/
    - assets/icons/
    - assets/icons/icon001/
    - assets/icons/icon001_active/
    - assets/icons/icon002/
    - assets/icons/icon002_active/
    - assets/icons/icon003/
    - assets/icons/icon003_active/
    - assets/icons/icon004/
    - assets/icons/icon004_active/
    - assets/icons/icon005/
    - assets/icons/icon005_active/
    - assets/icons/select_menus/
    - assets/images/loading/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
