name: data_repository

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  equatable: ^1.2.0

  auth_repository:
    path: ../auth_repository
